### ISSUE TITLE
Variables category doesn't show up

### ISSUE THREAD

**Issue by cvetelinandreev** [thomaswp/snap-replay#5]
Variables block category is empty.
 
![image](https://user-images.githubusercontent.com/11582890/151128224-d9ee1cd6-7994-45fb-8806-f7c54dc43374.png)

**Comment by thomaswp** [comment]
I'm not getting that issue. Could you send a test file to reproduce? And are there any console errors?

**Comment by thomaswp** [comment]
Ok, I was able to reproduce with the .zip you sent me, will try to debug.

**Comment by cvetelinandreev** [comment]
Ohh. I see now. It is broken only for my project. 
It could be that in my Variables category there are bunch of additional blocks from Snap libraries (Lists, etc), including Post to Smerge (Git for snap) and all of my custom block definitions. So my project is most probably broken. 

You might not want to waste much time on this issue.

**Comment by cvetelinandreev** [comment]
OK. I got this. There was a block imported from the Snap's List library. When I removed it manually from the xml I got it working. Closing the issue.
